rainbow_feature_A = "rainbow_feature_A"
rainbow_feature_B = "rainbow_feature_B"
rainbow_feature_C = "rainbow_feature_C"
rainbow_feature_D = "rainbow_feature_D"
rainbow_feature_G = "rainbow_feature_G"
rainbow_feature_X = "rainbow_feature_X"
rainbow_feature_U = "rainbow_feature_U"
rainbow_feature_V = "rainbow_feature_V"